#define K_DO
#define K_DOUBLE
#define K_ELSE
#define K_EXIT
#define K_FUNCTION
#define K_IF
#define K_INTEGER
#define K_PRINT_DOUBLE
#define K_PRINT_INTEGER
#define K_PRINT_STRING
#define K_PROCEDURE
#define K_PROGRAM
#define K_READ_DOUBLE
#define K_READ_INTEGER
#define K_READ_STRING
#define K_RETURN
#define K_STRING
#define K_THEN
#define K_WHILE
#define ASSIGN
#define ASSIGN_PLUS
#define ASSIGN_MINUS
#define ASSIGN_MULTIPLY
#define ASSIGN_DIVIDE
#define ASSIGN_MOD
#define COMMA
#define COMMENT
#define DAND
#define DIVIDE
#define DOR
#define DEQ
#define GEQ
#define GT
#define LBRACKET
#define LEQ
#define LCURLY
#define LPAREN
#define LT
#define MINUS
#define DECREMENT
#define MOD
#define MULTIPLY
#define NE
#define NOT
#define PERIOD
#define PLUS
#define INCREMENT
#define RBRACKET
#define RCURLY
#define RPAREN
#define SEMI